FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get update \
    && apt-get install -y git git-lfs python3 python3-pip \
    && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && git lfs install \
    && rm cuda-keyring_1.0-1_all.deb \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN git clone --depth 1 https://github.com/saidwivedi/TokenHMR \
    && cd TokenHMR && pip3 install --no-cache-dir -r requirements.txt 

RUN pip install --no-cache-dir git+https://github.com/facebookresearch/detectron2

ENV TORCH_CUDA_ARCH_LIST="8.6"
RUN pip install --no-cache-dir git+https://github.com/saidwivedi/PHALP

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 libegl1 wget \
    && pip install PyOpenGL-accelerate \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://huggingface.co/camenduru/NIKI/resolve/main/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl -P /TokenHMR/

WORKDIR /TokenHMR